# Generated by Django 3.2.1 on 2021-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210507_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
