# Generated by Django 3.2.1 on 2021-05-07 17:59

import api.helpers.analysis
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_upload_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrelationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation_data', models.JSONField(encoder=api.helpers.analysis.NpEncoder)),
                ('freq_distrib', models.JSONField(encoder=api.helpers.analysis.NpEncoder)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.upload')),
            ],
        ),
    ]
