# Generated by Django 3.2.1 on 2021-05-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_upload_application_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=512)),
                ('mean', models.DecimalField(decimal_places=4, max_digits=6)),
                ('mode', models.CharField(max_length=512)),
                ('median', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rel_freq', models.DecimalField(decimal_places=4, max_digits=6)),
                ('abs_freq', models.IntegerField()),
                ('spread', models.DecimalField(decimal_places=4, max_digits=6)),
                ('variance', models.DecimalField(decimal_places=4, max_digits=6)),
                ('stdev', models.DecimalField(decimal_places=4, max_digits=6)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.upload')),
            ],
        ),
    ]
